// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quiz_Web.Models.EF;

#nullable disable

namespace Quiz_Web.Migrations
{
    [DbContext(typeof(LearningPlatformContext))]
    partial class LearningPlatformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quiz_Web.Models.Entities.AttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptAnswerId"));

                    b.Property<string>("AnswerPayload")
                        .HasColumnType("text");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoGraded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GraderId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("AttemptAnswerId")
                        .HasName("PK__AttemptA__EC6FE54E12C4C90E");

                    b.HasIndex("AttemptId");

                    b.HasIndex("GraderId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F2398427591F1");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__488B0B0A3432F85C");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "CartId", "CourseId" }, "UQ_CartItems_Cart_Course")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Certificate", b =>
                {
                    b.Property<int>("CertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CertId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Serial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerifyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CertId")
                        .HasName("PK__Certific__E5BD38C54777E926");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "VerifyCode" }, "UQ_Certificates_Verify")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ContentShare", b =>
                {
                    b.Property<int>("ShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShareId"));

                    b.Property<bool>("CanAssign")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.HasKey("ShareId")
                        .HasName("PK__ContentS__D32A3FEEB660997F");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ContentShares");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ContentTag", b =>
                {
                    b.Property<int>("ContentTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentTagId"));

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ContentTagId")
                        .HasName("PK__ContentT__8FE574855212AE62");

                    b.HasIndex("TagId");

                    b.ToTable("ContentTags");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__C92D71A708E633CE");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex(new[] { "Slug" }, "UQ_Courses_Slug")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CategoryId")
                        .HasName("PK__CourseCa__19093A0B182C995A");

                    b.HasIndex(new[] { "Slug" }, "UQ__CourseCa__BC7B5FB6F93D6A58")
                        .IsUnique();

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseChapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChapterId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ChapterId")
                        .HasName("PK__CourseCh__0893A36A1A132FA9");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseChapters");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProgressId")
                        .HasName("PK__CoursePr__BAE29CA5857FEE59");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseProgress", (string)null);
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CoursePurchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PurchaseId")
                        .HasName("PK__CoursePu__6B0A6BBE3B207A0E");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CourseId");

                    b.ToTable("CoursePurchases");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2, 1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId")
                        .HasName("PK__CourseRe__74BC79CE283AC994");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CourseId" }, "IX_CourseReviews_Course");

                    b.ToTable("CourseReviews", t =>
                        {
                            t.HasTrigger("trg_UpdateCourseRating");
                        });
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ErrorLog", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ErrorId"));

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Stack")
                        .HasColumnType("text");

                    b.HasKey("ErrorId")
                        .HasName("PK__ErrorLog__35856A2A985924C4");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("FileId")
                        .HasName("PK__Files__6F0F98BFEE73AFB7");

                    b.HasIndex("OwnerId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Flashcard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<int?>("BackMediaId")
                        .HasColumnType("integer");

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("FrontMediaId")
                        .HasColumnType("integer");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CardId")
                        .HasName("PK__Flashcar__55FECDAE22B679D4");

                    b.HasIndex("BackMediaId");

                    b.HasIndex("FrontMediaId");

                    b.HasIndex("SetId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.FlashcardPracticeLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("EaseFactor")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int?>("NextIntervalDays")
                        .HasColumnType("integer");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SetId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LogId")
                        .HasName("PK__Flashcar__5E5486486B3F9ECA");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId");

                    b.ToTable("FlashcardPracticeLogs");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.FlashcardSet", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SetId"));

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("TagsText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("SetId")
                        .HasName("PK__Flashcar__7E08471D6D606900");

                    b.HasIndex("OwnerId");

                    b.ToTable("FlashcardSets");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FolderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.HasKey("FolderId")
                        .HasName("PK__Folders__ACD7107F7D93F1ED");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Course");

                    b.HasKey("LessonId")
                        .HasName("PK__Lessons__B084ACD022F804BF");

                    b.HasIndex("ChapterId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.LessonContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentId"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("RefId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ContentId")
                        .HasName("PK__LessonCo__2907A81E0574D749");

                    b.HasIndex(new[] { "LessonId", "OrderIndex" }, "IX_LessonContents_Lesson_Order");

                    b.ToTable("LessonContents");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Library", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LibraryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("LibraryId")
                        .HasName("PK__Librarie__A136475F60AB60B8");

                    b.HasIndex("OwnerId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E1246E72CAE");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BCF2D965192");

                    b.HasIndex("BuyerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("ItemId")
                        .HasName("PK__OrderIte__727E838BEDC4FB4C");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProviderRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A38D5990A46");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(1m);

                    b.Property<int?>("StemMediaId")
                        .HasColumnType("integer");

                    b.Property<string>("StemText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06FACA15F1129");

                    b.HasIndex("StemMediaId");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.QuestionClozeBlank", b =>
                {
                    b.Property<int>("BlankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlankId"));

                    b.Property<string>("AcceptRegex")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("BlankIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("CorrectText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("BlankId")
                        .HasName("PK__Question__F2BD63E7D863FE86");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionClozeBlanks");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.QuestionOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int?>("OptionMediaId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("OptionId")
                        .HasName("PK__Question__92C7A1FFD74642E5");

                    b.HasIndex("OptionMediaId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.QuestionRangeAnswer", b =>
                {
                    b.Property<int>("RangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RangeId"));

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Tolerance")
                        .HasColumnType("decimal(12, 4)");

                    b.HasKey("RangeId")
                        .HasName("PK__Question__6899CA14EF73FB91");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionRangeAnswers");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReminderId"));

                    b.Property<int>("RelatedId")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("TriggerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReminderId")
                        .HasName("PK__Reminder__01A83087F85448BC");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AFBE627BB");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6A098F8F5")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.SavedItem", b =>
                {
                    b.Property<int>("SavedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavedItemId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("SavedItemId")
                        .HasName("PK__SavedIte__1CBC88C8EC7DF7EA");

                    b.HasIndex("FolderId");

                    b.HasIndex("LibraryId");

                    b.ToTable("SavedItems");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CartId")
                        .HasName("PK__Shopping__51BCD7B7C43CC63D");

                    b.HasIndex(new[] { "UserId" }, "UQ_ShoppingCarts_UserId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TagId")
                        .HasName("PK__Tags__657CF9ACE6461BCF");

                    b.HasIndex(new[] { "Name" }, "UQ__Tags__737584F658F22BCC")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "UQ__Tags__BC7B5FB6571E0B70")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestId"));

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GradingMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime?>("OpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean");

                    b.Property<int?>("TimeLimitSec")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TestId")
                        .HasName("PK__Tests__8CC331602E3C05C8");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.TestAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptId"));

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSpentSec")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AttemptId")
                        .HasName("PK__TestAtte__891A68E64392AB4D");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CE98FF591");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053455164E7D")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.UserInterest", b =>
                {
                    b.Property<int>("UserInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserInterestId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserInterestId")
                        .HasName("PK__UserInte__28E6EBFEF254DB87");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "UserId", "CategoryId" }, "UQ_UserInterests_User_Category")
                        .IsUnique();

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId")
                        .HasName("PK__UserProf__1788CC4C494B0A05");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.UserSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailOptIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("PushOptIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UiTheme")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId")
                        .HasName("PK__UserSett__1788CC4C101AA23F");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.TestAttempt", "Attempt")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("AttemptId")
                        .IsRequired()
                        .HasConstraintName("FK_AAnswers_Attempt");

                    b.HasOne("Quiz_Web.Models.Entities.User", "Grader")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("GraderId")
                        .HasConstraintName("FK_AAnswers_Grader");

                    b.HasOne("Quiz_Web.Models.Entities.Question", "Question")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_AAnswers_Question");

                    b.Navigation("Attempt");

                    b.Navigation("Grader");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLogs_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CartItem", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.ShoppingCart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Cart");

                    b.HasOne("Quiz_Web.Models.Entities.Course", "Course")
                        .WithMany("CartItems")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Course");

                    b.Navigation("Cart");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Certificate", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Course", "Course")
                        .WithMany("Certificates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Certificates_Course");

                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Certificates_User");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ContentShare", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("ContentShares")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_ContentShares_Creator");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ContentTag", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Tag", "Tag")
                        .WithMany("ContentTags")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_ContentTags_Tag");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Course", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.CourseCategory", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Courses_Category");

                    b.HasOne("Quiz_Web.Models.Entities.User", "Owner")
                        .WithMany("Courses")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Courses_Owner");

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseChapter", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Course", "Course")
                        .WithMany("CourseChapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Chapters_Course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseProgress", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Course", "Course")
                        .WithMany("CourseProgresses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CoursePro__Cours__3493CFA7");

                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("CourseProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CoursePro__UserI__339FAB6E");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CoursePurchase", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "Buyer")
                        .WithMany("CoursePurchases")
                        .HasForeignKey("BuyerId")
                        .IsRequired()
                        .HasConstraintName("FK_CPurchases_Buyer");

                    b.HasOne("Quiz_Web.Models.Entities.Course", "Course")
                        .WithMany("CoursePurchases")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CPurchases_Course");

                    b.Navigation("Buyer");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseReview", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Course", "Course")
                        .WithMany("CourseReviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseRev__Cours__1CBC4616");

                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("CourseReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseRev__UserI__1DB06A4F");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.File", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "Owner")
                        .WithMany("Files")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Files_Owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Flashcard", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.File", "BackMedia")
                        .WithMany("FlashcardBackMedia")
                        .HasForeignKey("BackMediaId")
                        .HasConstraintName("FK_Flashcards_BackMedia");

                    b.HasOne("Quiz_Web.Models.Entities.File", "FrontMedia")
                        .WithMany("FlashcardFrontMedia")
                        .HasForeignKey("FrontMediaId")
                        .HasConstraintName("FK_Flashcards_FrontMedia");

                    b.HasOne("Quiz_Web.Models.Entities.FlashcardSet", "Set")
                        .WithMany("Flashcards")
                        .HasForeignKey("SetId")
                        .IsRequired()
                        .HasConstraintName("FK_Flashcards_Set");

                    b.Navigation("BackMedia");

                    b.Navigation("FrontMedia");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.FlashcardPracticeLog", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Flashcard", "Card")
                        .WithMany("FlashcardPracticeLogs")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK_FPL_Card");

                    b.HasOne("Quiz_Web.Models.Entities.FlashcardSet", "Set")
                        .WithMany("FlashcardPracticeLogs")
                        .HasForeignKey("SetId")
                        .IsRequired()
                        .HasConstraintName("FK_FPL_Set");

                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("FlashcardPracticeLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_FPL_User");

                    b.Navigation("Card");

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.FlashcardSet", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "Owner")
                        .WithMany("FlashcardSets")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_FlashcardSets_Owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Folder", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Library", "Library")
                        .WithMany("Folders")
                        .HasForeignKey("LibraryId")
                        .IsRequired()
                        .HasConstraintName("FK_Folders_Library");

                    b.HasOne("Quiz_Web.Models.Entities.Folder", "ParentFolder")
                        .WithMany("InverseParentFolder")
                        .HasForeignKey("ParentFolderId")
                        .HasConstraintName("FK_Folders_Parent");

                    b.Navigation("Library");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Lesson", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.CourseChapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lessons_Chapter");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.LessonContent", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Lesson", "Lesson")
                        .WithMany("LessonContents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LessonContents_Lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Library", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "Owner")
                        .WithMany("Libraries")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Libraries_Owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Notification", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Order", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_User");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Course", "Course")
                        .WithMany("OrderItems")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Course");

                    b.HasOne("Quiz_Web.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Order");

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Payment", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Question", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.File", "StemMedia")
                        .WithMany("Questions")
                        .HasForeignKey("StemMediaId")
                        .HasConstraintName("FK_Questions_StemMedia");

                    b.HasOne("Quiz_Web.Models.Entities.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Test");

                    b.Navigation("StemMedia");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.QuestionClozeBlank", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Question", "Question")
                        .WithMany("QuestionClozeBlanks")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QCloze_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.QuestionOption", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.File", "OptionMedia")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("OptionMediaId")
                        .HasConstraintName("FK_QOptions_Media");

                    b.HasOne("Quiz_Web.Models.Entities.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QOptions_Question");

                    b.Navigation("OptionMedia");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.QuestionRangeAnswer", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Question", "Question")
                        .WithMany("QuestionRangeAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QRange_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Reminder", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reminders_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.SavedItem", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Folder", "Folder")
                        .WithMany("SavedItems")
                        .HasForeignKey("FolderId")
                        .HasConstraintName("FK_SavedItems_Folder");

                    b.HasOne("Quiz_Web.Models.Entities.Library", "Library")
                        .WithMany("SavedItems")
                        .HasForeignKey("LibraryId")
                        .IsRequired()
                        .HasConstraintName("FK_SavedItems_Library");

                    b.Navigation("Folder");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ShoppingCart", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("Quiz_Web.Models.Entities.ShoppingCart", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingCarts_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Test", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "Owner")
                        .WithMany("Tests")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Tests_Owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.TestAttempt", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Test", "Test")
                        .WithMany("TestAttempts")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("FK_Attempts_Test");

                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Attempts_User");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.User", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.UserInterest", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.CourseCategory", "Category")
                        .WithMany("UserInterests")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_UserInterests_Category");

                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserInterests_User");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.UserProfile", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Quiz_Web.Models.Entities.UserProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserProfiles_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.UserSetting", b =>
                {
                    b.HasOne("Quiz_Web.Models.Entities.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("Quiz_Web.Models.Entities.UserSetting", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserSettings_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Course", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Certificates");

                    b.Navigation("CourseChapters");

                    b.Navigation("CourseProgresses");

                    b.Navigation("CoursePurchases");

                    b.Navigation("CourseReviews");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseCategory", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.CourseChapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.File", b =>
                {
                    b.Navigation("FlashcardBackMedia");

                    b.Navigation("FlashcardFrontMedia");

                    b.Navigation("QuestionOptions");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Flashcard", b =>
                {
                    b.Navigation("FlashcardPracticeLogs");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.FlashcardSet", b =>
                {
                    b.Navigation("FlashcardPracticeLogs");

                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Folder", b =>
                {
                    b.Navigation("InverseParentFolder");

                    b.Navigation("SavedItems");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Lesson", b =>
                {
                    b.Navigation("LessonContents");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Library", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("SavedItems");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Question", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("QuestionClozeBlanks");

                    b.Navigation("QuestionOptions");

                    b.Navigation("QuestionRangeAnswers");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Tag", b =>
                {
                    b.Navigation("ContentTags");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestAttempts");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.TestAttempt", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("Quiz_Web.Models.Entities.User", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("AuditLogs");

                    b.Navigation("Certificates");

                    b.Navigation("ContentShares");

                    b.Navigation("CourseProgresses");

                    b.Navigation("CoursePurchases");

                    b.Navigation("CourseReviews");

                    b.Navigation("Courses");

                    b.Navigation("Files");

                    b.Navigation("FlashcardPracticeLogs");

                    b.Navigation("FlashcardSets");

                    b.Navigation("Libraries");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Reminders");

                    b.Navigation("ShoppingCart");

                    b.Navigation("TestAttempts");

                    b.Navigation("Tests");

                    b.Navigation("UserInterests");

                    b.Navigation("UserProfile");

                    b.Navigation("UserSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
