name: .NET CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore Quiz_Web.sln

    - name: Build Project
      run: dotnet build Quiz_Web.sln --no-restore -c Release

    - name: Run Tests
      run: dotnet test Quiz_Web.sln --no-build --verbosity normal
